back_office_ville:
    resource: "@BackOfficeBundle/Controller/VilleController.php"
    prefix:   /adminbo
    type:     annotation

back_office_voiture:
    resource: "@BackOfficeBundle/Controller/VoitureController.php"
    prefix:   /adminbo
    type:     annotation

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /adminbo

front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
