web_service_homepage:
    path:     /
    defaults: { _controller: WebServiceBundle:Default:index }

web_service_search_homepage:
    path:     /{search}
    defaults: { _controller: WebServiceBundle:Default:search }

web_service_details_homepage:
    path:     /details/{id}
    defaults: { _controller: WebServiceBundle:Default:details }

search_depart_homepage:
    path:     /depart/{search}
    defaults: { _controller: WebServiceBundle:Default:searchDepart }

search_arrivee_homepage:
    path:     /arrivee/{search}
    defaults: { _controller: WebServiceBundle:Default:searchArrivee }
