web_service_homepage:
    path:     /
    defaults: { _controller: WebServiceBundle:Default:index }

web_service_search_homepage:
    path:     /{search}
    defaults: { _controller: WebServiceBundle:Default:search }
